package filmDataBaseApp;

public enum Genre {

	SURREAL, ACTION, ADVENTURE, COMEDY, CRIME, DRAMA, FANTASY, HISTORICAL,
	HORROR, MAGICAL, MYSTERY, PARANOID, PHILOSOPHICAL, POLITICAL, ROMANCE, 
	SAGA, SATIRE, SCIFI, SLICEOFLIFE, SPECULATIVE, THRILLER, URBAN,
	WESTERN, ASIAN, FAMILY, ANIMATION, BIOGRAPHY, SPORT;
}
